### ISSUE TITLE
Purepursuit is not launching

### ISSUE THREAD

**Issue by rdpujari** [f1tenth-dev/simulator#5] opened 2020-02-10 10:22 UTC
when I launch this command, roslaunch f1tenth-sim purepursuit_one_car.launch, it shows this error and starts killing all the process and exits the terminal.
RLException: Roslaunch got a 'No such file or directory' error while attempting to run:
Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file.

**Comment by f1tenth-dev** [comment] 2020-02-12 06:07
Can you upload log files so that the source of the problem is clear?

**Comment by simonrozsival** [comment] 2020-03-29 09:53
The python code contains some hard-coded file paths which probably don't match your local directory structure. For example I had to make this change in the `/scripts/adaptive_lookahead.py` file:
```python
-    file_path = os.path.expanduser('~/catkin_ws/src/f1tenth_purepursuit/sectors/{}.csv'.format(sector_list_name))
+    file_path = os.path.join(os.path.dirname(__file__), '../sectors/{}.csv'.format(sector_list_name))
```
There are a few places where the absolute file path is used and where the `f1tenth_purepursuit` repo name appears (https://github.com/search?q=f1tenth_purepursuit&type=Code, it is probably an old name of a repo and they forgot to change the paths after they moved it to this repo called `simulator`).

~I'll try to make a PR which fixes these paths if I have time during April if it isn't fixed by then.~ _EDIT: It wasn't much work, so I reconsidered it and I created the PR right now before I forget about it._

**Comment by varundevsukhil** [comment] 2020-03-29 22:58
The path variables have been modified, this issue has been resolved.

**Closed as completed by varundevsukhil** 2020-03-29 22:58 UTC
